registerExercise({
  id: "modernSounds",
  label: "Modern Sounds",
  inMenu: false,
  items: [
    "C<sup><small> </small></sup>q",
    "C<sup><small> </small></sup>sus4",
    "C<sup><small> </small></sup>sus2",
    "C<sup><small> </small></sup>7sus4",
    "C<sup><small> </small></sup>sus2sus4",
    "C<sup><small> </small></sup>q10",
    "C<sup><small> </small></sup>6sus2",
    "C<sup><small> </small></sup>add2",
    "C<sup><small> </small></sup>add2 1st Inv",
    "C<sup><small> </small></sup>add2 2nd Inv",
    "C<sup><small> </small></sup>add4",
    "C<sup><small> </small></sup>add4 1st Inv",
    "C<sup><small> </small></sup>add4 2nd Inv",
    "C<sup><small> </small></sup>madd4",
    "C<sup><small> </small></sup>madd4 1st Inv",
    "C<sup><small> </small></sup>madd4 2nd Inv",
    "C<sup><small> </small></sup>add#2 2nd Inv",
    "C<sup><small> </small></sup>madd#4",
    "C<sup><small> </small></sup>q",
    "C<sup><small> </small></sup>sus4",
    "C<sup><small> </small></sup>sus2",
    "C<sup><small> </small></sup>7sus4",
    "C<sup><small> </small></sup>sus2sus4",
    "C<sup><small> </small></sup>q10",
    "C<sup><small> </small></sup>6sus2",
    "C<sup><small> </small></sup>add2",
    "C<sup><small> </small></sup>add2 1st Inv",
    "C<sup><small> </small></sup>add2 2nd Inv",
    "C<sup><small> </small></sup>add4",
    "C<sup><small> </small></sup>add4 1st Inv",
    "C<sup><small> </small></sup>add4 2nd Inv",
    "C<sup><small> </small></sup>madd4",
    "C<sup><small> </small></sup>madd4 1st Inv",
    "C<sup><small> </small></sup>madd4 2nd Inv",
    "C<sup><small> </small></sup>add#2 2nd Inv",
    "C<sup><small> </small></sup>madd#4",
    "C<sup><small>&#9839</small></sup>q",
    "C<sup><small>&#9839</small></sup>sus4",
    "C<sup><small>&#9839</small></sup>sus2",
    "C<sup><small>&#9839</small></sup>7sus4",
    "C<sup><small>&#9839</small></sup>sus2sus4",
    "C<sup><small>&#9839</small></sup>q10",
    "C<sup><small>&#9839</small></sup>6sus2",
    "C<sup><small>&#9839</small></sup>add2",
    "C<sup><small>&#9839</small></sup>add2 1st Inv",
    "C<sup><small>&#9839</small></sup>add2 2nd Inv",
    "C<sup><small>&#9839</small></sup>add4",
    "C<sup><small>&#9839</small></sup>add4 1st Inv",
    "C<sup><small>&#9839</small></sup>add4 2nd Inv",
    "C<sup><small>&#9839</small></sup>madd4",
    "C<sup><small>&#9839</small></sup>madd4 1st Inv",
    "C<sup><small>&#9839</small></sup>madd4 2nd Inv",
    "C<sup><small>&#9839</small></sup>add#2 2nd Inv",
    "C<sup><small>&#9839</small></sup>madd#4",
    "D<sup><small>&#9837</small></sup>q",
    "D<sup><small>&#9837</small></sup>sus4",
    "D<sup><small>&#9837</small></sup>sus2",
    "D<sup><small>&#9837</small></sup>7sus4",
    "D<sup><small>&#9837</small></sup>sus2sus4",
    "D<sup><small>&#9837</small></sup>q10",
    "D<sup><small>&#9837</small></sup>6sus2",
    "D<sup><small>&#9837</small></sup>add2",
    "D<sup><small>&#9837</small></sup>add2 1st Inv",
    "D<sup><small>&#9837</small></sup>add2 2nd Inv",
    "D<sup><small>&#9837</small></sup>add4",
    "D<sup><small>&#9837</small></sup>add4 1st Inv",
    "D<sup><small>&#9837</small></sup>add4 2nd Inv",
    "D<sup><small>&#9837</small></sup>madd4",
    "D<sup><small>&#9837</small></sup>madd4 1st Inv",
    "D<sup><small>&#9837</small></sup>madd4 2nd Inv",
    "D<sup><small>&#9837</small></sup>add#2 2nd Inv",
    "D<sup><small>&#9837</small></sup>madd#4",
    "D<sup><small> </small></sup>q",
    "D<sup><small> </small></sup>sus4",
    "D<sup><small> </small></sup>sus2",
    "D<sup><small> </small></sup>7sus4",
    "D<sup><small> </small></sup>sus2sus4",
    "D<sup><small> </small></sup>q10",
    "D<sup><small> </small></sup>6sus2",
    "D<sup><small> </small></sup>add2",
    "D<sup><small> </small></sup>add2 1st Inv",
    "D<sup><small> </small></sup>add2 2nd Inv",
    "D<sup><small> </small></sup>add4",
    "D<sup><small> </small></sup>add4 1st Inv",
    "D<sup><small> </small></sup>add4 2nd Inv",
    "D<sup><small> </small></sup>madd4",
    "D<sup><small> </small></sup>madd4 1st Inv",
    "D<sup><small> </small></sup>madd4 2nd Inv",
    "D<sup><small> </small></sup>add#2 2nd Inv",
    "D<sup><small> </small></sup>madd#4",
    "D<sup><small> </small></sup>q",
    "D<sup><small> </small></sup>sus4",
    "D<sup><small> </small></sup>sus2",
    "D<sup><small> </small></sup>7sus4",
    "D<sup><small> </small></sup>sus2sus4",
    "D<sup><small> </small></sup>q10",
    "D<sup><small> </small></sup>6sus2",
    "D<sup><small> </small></sup>add2",
    "D<sup><small> </small></sup>add2 1st Inv",
    "D<sup><small> </small></sup>add2 2nd Inv",
    "D<sup><small> </small></sup>add4",
    "D<sup><small> </small></sup>add4 1st Inv",
    "D<sup><small> </small></sup>add4 2nd Inv",
    "D<sup><small> </small></sup>madd4",
    "D<sup><small> </small></sup>madd4 1st Inv",
    "D<sup><small> </small></sup>madd4 2nd Inv",
    "D<sup><small> </small></sup>add#2 2nd Inv",
    "D<sup><small> </small></sup>madd#4",
    "D<sup><small>&#9839</small></sup>q",
    "D<sup><small>&#9839</small></sup>sus4",
    "D<sup><small>&#9839</small></sup>sus2",
    "D<sup><small>&#9839</small></sup>7sus4",
    "D<sup><small>&#9839</small></sup>sus2sus4",
    "D<sup><small>&#9839</small></sup>q10",
    "D<sup><small>&#9839</small></sup>6sus2",
    "D<sup><small>&#9839</small></sup>add2",
    "D<sup><small>&#9839</small></sup>add2 1st Inv",
    "D<sup><small>&#9839</small></sup>add2 2nd Inv",
    "D<sup><small>&#9839</small></sup>add4",
    "D<sup><small>&#9839</small></sup>add4 1st Inv",
    "D<sup><small>&#9839</small></sup>add4 2nd Inv",
    "D<sup><small>&#9839</small></sup>madd4",
    "D<sup><small>&#9839</small></sup>madd4 1st Inv",
    "D<sup><small>&#9839</small></sup>madd4 2nd Inv",
    "D<sup><small>&#9839</small></sup>add#2 2nd Inv",
    "D<sup><small>&#9839</small></sup>madd#4",
    "E<sup><small>&#9837</small></sup>q",
    "E<sup><small>&#9837</small></sup>sus4",
    "E<sup><small>&#9837</small></sup>sus2",
    "E<sup><small>&#9837</small></sup>7sus4",
    "E<sup><small>&#9837</small></sup>sus2sus4",
    "E<sup><small>&#9837</small></sup>q10",
    "E<sup><small>&#9837</small></sup>6sus2",
    "E<sup><small>&#9837</small></sup>add2",
    "E<sup><small>&#9837</small></sup>add2 1st Inv",
    "E<sup><small>&#9837</small></sup>add2 2nd Inv",
    "E<sup><small>&#9837</small></sup>add4",
    "E<sup><small>&#9837</small></sup>add4 1st Inv",
    "E<sup><small>&#9837</small></sup>add4 2nd Inv",
    "E<sup><small>&#9837</small></sup>madd4",
    "E<sup><small>&#9837</small></sup>madd4 1st Inv",
    "E<sup><small>&#9837</small></sup>madd4 2nd Inv",
    "E<sup><small>&#9837</small></sup>add#2 2nd Inv",
    "E<sup><small>&#9837</small></sup>madd#4",
    "E<sup><small> </small></sup>q",
    "E<sup><small> </small></sup>sus4",
    "E<sup><small> </small></sup>sus2",
    "E<sup><small> </small></sup>7sus4",
    "E<sup><small> </small></sup>sus2sus4",
    "E<sup><small> </small></sup>q10",
    "E<sup><small> </small></sup>6sus2",
    "E<sup><small> </small></sup>add2",
    "E<sup><small> </small></sup>add2 1st Inv",
    "E<sup><small> </small></sup>add2 2nd Inv",
    "E<sup><small> </small></sup>add4",
    "E<sup><small> </small></sup>add4 1st Inv",
    "E<sup><small> </small></sup>add4 2nd Inv",
    "E<sup><small> </small></sup>madd4",
    "E<sup><small> </small></sup>madd4 1st Inv",
    "E<sup><small> </small></sup>madd4 2nd Inv",
    "E<sup><small> </small></sup>add#2 2nd Inv",
    "E<sup><small> </small></sup>madd#4",
    "E<sup><small> </small></sup>q",
    "E<sup><small> </small></sup>sus4",
    "E<sup><small> </small></sup>sus2",
    "E<sup><small> </small></sup>7sus4",
    "E<sup><small> </small></sup>sus2sus4",
    "E<sup><small> </small></sup>q10",
    "E<sup><small> </small></sup>6sus2",
    "E<sup><small> </small></sup>add2",
    "E<sup><small> </small></sup>add2 1st Inv",
    "E<sup><small> </small></sup>add2 2nd Inv",
    "E<sup><small> </small></sup>add4",
    "E<sup><small> </small></sup>add4 1st Inv",
    "E<sup><small> </small></sup>add4 2nd Inv",
    "E<sup><small> </small></sup>madd4",
    "E<sup><small> </small></sup>madd4 1st Inv",
    "E<sup><small> </small></sup>madd4 2nd Inv",
    "E<sup><small> </small></sup>add#2 2nd Inv",
    "E<sup><small> </small></sup>madd#4",
    "F<sup><small> </small></sup>q",
    "F<sup><small> </small></sup>sus4",
    "F<sup><small> </small></sup>sus2",
    "F<sup><small> </small></sup>7sus4",
    "F<sup><small> </small></sup>sus2sus4",
    "F<sup><small> </small></sup>q10",
    "F<sup><small> </small></sup>6sus2",
    "F<sup><small> </small></sup>add2",
    "F<sup><small> </small></sup>add2 1st Inv",
    "F<sup><small> </small></sup>add2 2nd Inv",
    "F<sup><small> </small></sup>add4",
    "F<sup><small> </small></sup>add4 1st Inv",
    "F<sup><small> </small></sup>add4 2nd Inv",
    "F<sup><small> </small></sup>madd4",
    "F<sup><small> </small></sup>madd4 1st Inv",
    "F<sup><small> </small></sup>madd4 2nd Inv",
    "F<sup><small> </small></sup>add#2 2nd Inv",
    "F<sup><small> </small></sup>madd#4",
    "F<sup><small> </small></sup>q",
    "F<sup><small> </small></sup>sus4",
    "F<sup><small> </small></sup>sus2",
    "F<sup><small> </small></sup>7sus4",
    "F<sup><small> </small></sup>sus2sus4",
    "F<sup><small> </small></sup>q10",
    "F<sup><small> </small></sup>6sus2",
    "F<sup><small> </small></sup>add2",
    "F<sup><small> </small></sup>add2 1st Inv",
    "F<sup><small> </small></sup>add2 2nd Inv",
    "F<sup><small> </small></sup>add4",
    "F<sup><small> </small></sup>add4 1st Inv",
    "F<sup><small> </small></sup>add4 2nd Inv",
    "F<sup><small> </small></sup>madd4",
    "F<sup><small> </small></sup>madd4 1st Inv",
    "F<sup><small> </small></sup>madd4 2nd Inv",
    "F<sup><small> </small></sup>add#2 2nd Inv",
    "F<sup><small> </small></sup>madd#4",
    "F<sup><small>&#9839</small></sup>q",
    "F<sup><small>&#9839</small></sup>sus4",
    "F<sup><small>&#9839</small></sup>sus2",
    "F<sup><small>&#9839</small></sup>7sus4",
    "F<sup><small>&#9839</small></sup>sus2sus4",
    "F<sup><small>&#9839</small></sup>q10",
    "F<sup><small>&#9839</small></sup>6sus2",
    "F<sup><small>&#9839</small></sup>add2",
    "F<sup><small>&#9839</small></sup>add2 1st Inv",
    "F<sup><small>&#9839</small></sup>add2 2nd Inv",
    "F<sup><small>&#9839</small></sup>add4",
    "F<sup><small>&#9839</small></sup>add4 1st Inv",
    "F<sup><small>&#9839</small></sup>add4 2nd Inv",
    "F<sup><small>&#9839</small></sup>madd4",
    "F<sup><small>&#9839</small></sup>madd4 1st Inv",
    "F<sup><small>&#9839</small></sup>madd4 2nd Inv",
    "F<sup><small>&#9839</small></sup>add#2 2nd Inv",
    "F<sup><small>&#9839</small></sup>madd#4",
    "G<sup><small>&#9837</small></sup>q",
    "G<sup><small>&#9837</small></sup>sus4",
    "G<sup><small>&#9837</small></sup>sus2",
    "G<sup><small>&#9837</small></sup>7sus4",
    "G<sup><small>&#9837</small></sup>sus2sus4",
    "G<sup><small>&#9837</small></sup>q10",
    "G<sup><small>&#9837</small></sup>6sus2",
    "G<sup><small>&#9837</small></sup>add2",
    "G<sup><small>&#9837</small></sup>add2 1st Inv",
    "G<sup><small>&#9837</small></sup>add2 2nd Inv",
    "G<sup><small>&#9837</small></sup>add4",
    "G<sup><small>&#9837</small></sup>add4 1st Inv",
    "G<sup><small>&#9837</small></sup>add4 2nd Inv",
    "G<sup><small>&#9837</small></sup>madd4",
    "G<sup><small>&#9837</small></sup>madd4 1st Inv",
    "G<sup><small>&#9837</small></sup>madd4 2nd Inv",
    "G<sup><small>&#9837</small></sup>add#2 2nd Inv",
    "G<sup><small>&#9837</small></sup>madd#4",
    "G<sup><small> </small></sup>q",
    "G<sup><small> </small></sup>sus4",
    "G<sup><small> </small></sup>sus2",
    "G<sup><small> </small></sup>7sus4",
    "G<sup><small> </small></sup>sus2sus4",
    "G<sup><small> </small></sup>q10",
    "G<sup><small> </small></sup>6sus2",
    "G<sup><small> </small></sup>add2",
    "G<sup><small> </small></sup>add2 1st Inv",
    "G<sup><small> </small></sup>add2 2nd Inv",
    "G<sup><small> </small></sup>add4",
    "G<sup><small> </small></sup>add4 1st Inv",
    "G<sup><small> </small></sup>add4 2nd Inv",
    "G<sup><small> </small></sup>madd4",
    "G<sup><small> </small></sup>madd4 1st Inv",
    "G<sup><small> </small></sup>madd4 2nd Inv",
    "G<sup><small> </small></sup>add#2 2nd Inv",
    "G<sup><small> </small></sup>madd#4",
    "G<sup><small> </small></sup>q",
    "G<sup><small> </small></sup>sus4",
    "G<sup><small> </small></sup>sus2",
    "G<sup><small> </small></sup>7sus4",
    "G<sup><small> </small></sup>sus2sus4",
    "G<sup><small> </small></sup>q10",
    "G<sup><small> </small></sup>6sus2",
    "G<sup><small> </small></sup>add2",
    "G<sup><small> </small></sup>add2 1st Inv",
    "G<sup><small> </small></sup>add2 2nd Inv",
    "G<sup><small> </small></sup>add4",
    "G<sup><small> </small></sup>add4 1st Inv",
    "G<sup><small> </small></sup>add4 2nd Inv",
    "G<sup><small> </small></sup>madd4",
    "G<sup><small> </small></sup>madd4 1st Inv",
    "G<sup><small> </small></sup>madd4 2nd Inv",
    "G<sup><small> </small></sup>add#2 2nd Inv",
    "G<sup><small> </small></sup>madd#4",
    "G<sup><small>&#9839</small></sup>q",
    "G<sup><small>&#9839</small></sup>sus4",
    "G<sup><small>&#9839</small></sup>sus2",
    "G<sup><small>&#9839</small></sup>7sus4",
    "G<sup><small>&#9839</small></sup>sus2sus4",
    "G<sup><small>&#9839</small></sup>q10",
    "G<sup><small>&#9839</small></sup>6sus2",
    "G<sup><small>&#9839</small></sup>add2",
    "G<sup><small>&#9839</small></sup>add2 1st Inv",
    "G<sup><small>&#9839</small></sup>add2 2nd Inv",
    "G<sup><small>&#9839</small></sup>add4",
    "G<sup><small>&#9839</small></sup>add4 1st Inv",
    "G<sup><small>&#9839</small></sup>add4 2nd Inv",
    "G<sup><small>&#9839</small></sup>madd4",
    "G<sup><small>&#9839</small></sup>madd4 1st Inv",
    "G<sup><small>&#9839</small></sup>madd4 2nd Inv",
    "G<sup><small>&#9839</small></sup>add#2 2nd Inv",
    "G<sup><small>&#9839</small></sup>madd#4",
    "A<sup><small>&#9837</small></sup>q",
    "A<sup><small>&#9837</small></sup>sus4",
    "A<sup><small>&#9837</small></sup>sus2",
    "A<sup><small>&#9837</small></sup>7sus4",
    "A<sup><small>&#9837</small></sup>sus2sus4",
    "A<sup><small>&#9837</small></sup>q10",
    "A<sup><small>&#9837</small></sup>6sus2",
    "A<sup><small>&#9837</small></sup>add2",
    "A<sup><small>&#9837</small></sup>add2 1st Inv",
    "A<sup><small>&#9837</small></sup>add2 2nd Inv",
    "A<sup><small>&#9837</small></sup>add4",
    "A<sup><small>&#9837</small></sup>add4 1st Inv",
    "A<sup><small>&#9837</small></sup>add4 2nd Inv",
    "A<sup><small>&#9837</small></sup>madd4",
    "A<sup><small>&#9837</small></sup>madd4 1st Inv",
    "A<sup><small>&#9837</small></sup>madd4 2nd Inv",
    "A<sup><small>&#9837</small></sup>add#2 2nd Inv",
    "A<sup><small>&#9837</small></sup>madd#4",
    "A<sup><small> </small></sup>q",
    "A<sup><small> </small></sup>sus4",
    "A<sup><small> </small></sup>sus2",
    "A<sup><small> </small></sup>7sus4",
    "A<sup><small> </small></sup>sus2sus4",
    "A<sup><small> </small></sup>q10",
    "A<sup><small> </small></sup>6sus2",
    "A<sup><small> </small></sup>add2",
    "A<sup><small> </small></sup>add2 1st Inv",
    "A<sup><small> </small></sup>add2 2nd Inv",
    "A<sup><small> </small></sup>add4",
    "A<sup><small> </small></sup>add4 1st Inv",
    "A<sup><small> </small></sup>add4 2nd Inv",
    "A<sup><small> </small></sup>madd4",
    "A<sup><small> </small></sup>madd4 1st Inv",
    "A<sup><small> </small></sup>madd4 2nd Inv",
    "A<sup><small> </small></sup>add#2 2nd Inv",
    "A<sup><small> </small></sup>madd#4",
    "A<sup><small> </small></sup>q",
    "A<sup><small> </small></sup>sus4",
    "A<sup><small> </small></sup>sus2",
    "A<sup><small> </small></sup>7sus4",
    "A<sup><small> </small></sup>sus2sus4",
    "A<sup><small> </small></sup>q10",
    "A<sup><small> </small></sup>6sus2",
    "A<sup><small> </small></sup>add2",
    "A<sup><small> </small></sup>add2 1st Inv",
    "A<sup><small> </small></sup>add2 2nd Inv",
    "A<sup><small> </small></sup>add4",
    "A<sup><small> </small></sup>add4 1st Inv",
    "A<sup><small> </small></sup>add4 2nd Inv",
    "A<sup><small> </small></sup>madd4",
    "A<sup><small> </small></sup>madd4 1st Inv",
    "A<sup><small> </small></sup>madd4 2nd Inv",
    "A<sup><small> </small></sup>add#2 2nd Inv",
    "A<sup><small> </small></sup>madd#4",
    "A<sup><small>&#9839</small></sup>q",
    "A<sup><small>&#9839</small></sup>sus4",
    "A<sup><small>&#9839</small></sup>sus2",
    "A<sup><small>&#9839</small></sup>7sus4",
    "A<sup><small>&#9839</small></sup>sus2sus4",
    "A<sup><small>&#9839</small></sup>q10",
    "A<sup><small>&#9839</small></sup>6sus2",
    "A<sup><small>&#9839</small></sup>add2",
    "A<sup><small>&#9839</small></sup>add2 1st Inv",
    "A<sup><small>&#9839</small></sup>add2 2nd Inv",
    "A<sup><small>&#9839</small></sup>add4",
    "A<sup><small>&#9839</small></sup>add4 1st Inv",
    "A<sup><small>&#9839</small></sup>add4 2nd Inv",
    "A<sup><small>&#9839</small></sup>madd4",
    "A<sup><small>&#9839</small></sup>madd4 1st Inv",
    "A<sup><small>&#9839</small></sup>madd4 2nd Inv",
    "A<sup><small>&#9839</small></sup>add#2 2nd Inv",
    "A<sup><small>&#9839</small></sup>madd#4",
    "B<sup><small>&#9837</small></sup>q",
    "B<sup><small>&#9837</small></sup>sus4",
    "B<sup><small>&#9837</small></sup>sus2",
    "B<sup><small>&#9837</small></sup>7sus4",
    "B<sup><small>&#9837</small></sup>sus2sus4",
    "B<sup><small>&#9837</small></sup>q10",
    "B<sup><small>&#9837</small></sup>6sus2",
    "B<sup><small>&#9837</small></sup>add2",
    "B<sup><small>&#9837</small></sup>add2 1st Inv",
    "B<sup><small>&#9837</small></sup>add2 2nd Inv",
    "B<sup><small>&#9837</small></sup>add4",
    "B<sup><small>&#9837</small></sup>add4 1st Inv",
    "B<sup><small>&#9837</small></sup>add4 2nd Inv",
    "B<sup><small>&#9837</small></sup>madd4",
    "B<sup><small>&#9837</small></sup>madd4 1st Inv",
    "B<sup><small>&#9837</small></sup>madd4 2nd Inv",
    "B<sup><small>&#9837</small></sup>add#2 2nd Inv",
    "B<sup><small>&#9837</small></sup>madd#4",
    "B<sup><small> </small></sup>q",
    "B<sup><small> </small></sup>sus4",
    "B<sup><small> </small></sup>sus2",
    "B<sup><small> </small></sup>7sus4",
    "B<sup><small> </small></sup>sus2sus4",
    "B<sup><small> </small></sup>q10",
    "B<sup><small> </small></sup>6sus2",
    "B<sup><small> </small></sup>add2",
    "B<sup><small> </small></sup>add2 1st Inv",
    "B<sup><small> </small></sup>add2 2nd Inv",
    "B<sup><small> </small></sup>add4",
    "B<sup><small> </small></sup>add4 1st Inv",
    "B<sup><small> </small></sup>add4 2nd Inv",
    "B<sup><small> </small></sup>madd4",
    "B<sup><small> </small></sup>madd4 1st Inv",
    "B<sup><small> </small></sup>madd4 2nd Inv",
    "B<sup><small> </small></sup>add#2 2nd Inv",
    "B<sup><small> </small></sup>madd#4",
    "B<sup><small> </small></sup>q",
    "B<sup><small> </small></sup>sus4",
    "B<sup><small> </small></sup>sus2",
    "B<sup><small> </small></sup>7sus4",
    "B<sup><small> </small></sup>sus2sus4",
    "B<sup><small> </small></sup>q10",
    "B<sup><small> </small></sup>6sus2",
    "B<sup><small> </small></sup>add2",
    "B<sup><small> </small></sup>add2 1st Inv",
    "B<sup><small> </small></sup>add2 2nd Inv",
    "B<sup><small> </small></sup>add4",
    "B<sup><small> </small></sup>add4 1st Inv",
    "B<sup><small> </small></sup>add4 2nd Inv",
    "B<sup><small> </small></sup>madd4",
    "B<sup><small> </small></sup>madd4 1st Inv",
    "B<sup><small> </small></sup>madd4 2nd Inv",
    "B<sup><small> </small></sup>add#2 2nd Inv",
    "B<sup><small> </small></sup>madd#4"

  ]
});
