registerExercise({
  id: "scales",
  label: "Scales",
  inMenu: true,
  items: [
    "Major",
    "Dorian",
    "Phrygian",
    "Lydian",
    "Mixolydian",
    "Aeolian",
    "Locrian",
    "Harmonic minor",
    "Melodic minor",
    "Harmonic major",
    "Dorian &#9837;2",
    "Lydian augmented",
    "Lydian dominant",
    "Mixolydian &#9837;6",
    "Locrian &#9838;2",
    "Altered",
    "Phrygian dominant",
    "Whole tone",
    "Half-whole diminished",
    "Whole-half diminished",
    "Major pentatonic",
    "Minor pentatonic",
    "Blues",
    "Major blues",
    "Bebop major",
    "Bebop dominant",
    "Bebop minor"
  ]
});
